# Site
name: 'Aderson'
title: 'Aderson'
longtitle: 'This is Adersons blog.'
description: 'This is Adersons blog.'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
url: 'https://aderson.com'
baseurl: '/'
disqus: ''
email: 'aderson.oliveira@gmail.com'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    aderson:
      name:           Aderson
      site:           https://solocoder.com
      avatar:         /assets/images/aderson.jpg
      bio:            "Hello Hello! Aderson Oliveira Here! I'm a Solo Coder."
      email:          aderson.oliveira@gmail.com
      twitter:        https://twitter.com/adersonoliveira
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: aderson
      avatar: /assets/images/aderson.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]